[package]
name = "uva-game-theory"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Henry Zwart <@henry-zwart>"]
license = "MIT"
description = "An unofficial template for assignments in the University of Amsterdam Game Theory course"
repository = "https://github.com/henry-zwart/uva-game-theory"
keywords = ["report", "university", "student"]
categories = ["report"]
compiler = "0.13.1"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
